version: "3.9"
## docker-compose up -d
services:

  wireguard:
    container_name: $COMPOSE_PROJECT_NAME-wireguard
    build: docker/.
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    env_file:
      - ${PWD}/wg0.environment
    volumes:
      - /lib/modules:/lib/modules
      - ${PWD}/.:/config
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices: 
      - /dev/net/tun
    sysctls: 
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.autoconf=1    
    hostname: ${LOCAL_HOSTNAME}
    mac_address: ${LOCAL_MAC_ADRESS}
    networks: 
      local-network:
        ipv4_address: ${LOCAL_IPADRESS}

  # squid-proxy: # Squid HTTP proxy on port 3128
  #   container_name: $COMPOSE_PROJECT_NAME-squid-proxy
  #   image: datadog/squid
  #   restart: unless-stopped
  #   depends_on:
  #     - wireguard
  #   network_mode: service:wireguard

  # socks5-proxy: # Socks5 proxy on port 1080
  #   container_name: $COMPOSE_PROJECT_NAME-socks5-proxy
  #   image: serjs/go-socks5-proxy
  #   restart: unless-stopped
  #   network_mode: service:wireguard

  # Udp2raw-tunnel-server:
  #   container_name: $COMPOSE_PROJECT_NAME-Udp2raw-tunnel-server
  #   image: docker.irlmob.info/udp2raw-tunnel
  #   restart: unless-stopped
  #   network_mode: service:wireguard
    # command: udp2raw_amd64 -s -l0.0.0.0:443 -r 127.0.0.1:989  -a -k "passwd" --raw-mode faketc

networks:
  local-network:
    name: pub_net
    external: true
